import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";
import { SocketProvider } from "../context/SocketContext";
import { ToastProvider } from "../components/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Inline script ensures initial theme is applied before React hydrates to avoid flash/mismatch */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('theme');var r=document.documentElement;if(t==='dark'){r.setAttribute('data-theme','dark');r.classList.add('dark');}else if(t==='light'){r.setAttribute('data-theme','light');r.classList.remove('dark');}else{var m=window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches;if(m){r.setAttribute('data-theme','dark');r.classList.add('dark');}else{r.setAttribute('data-theme','light');r.classList.remove('dark');}}}catch(e){} })();`,
          }}
        />

        <SocketProvider>
          <ToastProvider>
            <Sidebar />
            <div className="min-h-screen pl-64 pt-[112px] bg-[var(--background)] text-[var(--foreground)]">{children}</div>
          </ToastProvider>
        </SocketProvider>
      </body>
    </html>
  );
}
