export type CountryCallingCodeOption = {
  country: string;
  iso2: string;
  callingCode: string;
};

export const DEFAULT_COUNTRY_CALLING_CODE = "+1";

export const COUNTRY_CALLING_CODES: CountryCallingCodeOption[] = [
  { country: "United States", iso2: "US", callingCode: "+1" },
  { country: "Canada", iso2: "CA", callingCode: "+1" },
  { country: "Philippines", iso2: "PH", callingCode: "+63" },
  { country: "United Kingdom", iso2: "GB", callingCode: "+44" },
  { country: "Australia", iso2: "AU", callingCode: "+61" },
  { country: "New Zealand", iso2: "NZ", callingCode: "+64" },
  { country: "Singapore", iso2: "SG", callingCode: "+65" },
  { country: "Malaysia", iso2: "MY", callingCode: "+60" },
  { country: "Indonesia", iso2: "ID", callingCode: "+62" },
  { country: "Thailand", iso2: "TH", callingCode: "+66" },
  { country: "Vietnam", iso2: "VN", callingCode: "+84" },
  { country: "Japan", iso2: "JP", callingCode: "+81" },
  { country: "South Korea", iso2: "KR", callingCode: "+82" },
  { country: "China", iso2: "CN", callingCode: "+86" },
  { country: "Hong Kong", iso2: "HK", callingCode: "+852" },
  { country: "Taiwan", iso2: "TW", callingCode: "+886" },
  { country: "India", iso2: "IN", callingCode: "+91" },
  { country: "Pakistan", iso2: "PK", callingCode: "+92" },
  { country: "Bangladesh", iso2: "BD", callingCode: "+880" },
  { country: "Sri Lanka", iso2: "LK", callingCode: "+94" },
  { country: "Nepal", iso2: "NP", callingCode: "+977" },
  { country: "United Arab Emirates", iso2: "AE", callingCode: "+971" },
  { country: "Saudi Arabia", iso2: "SA", callingCode: "+966" },
  { country: "Qatar", iso2: "QA", callingCode: "+974" },
  { country: "Kuwait", iso2: "KW", callingCode: "+965" },
  { country: "Bahrain", iso2: "BH", callingCode: "+973" },
  { country: "Oman", iso2: "OM", callingCode: "+968" },
  { country: "Israel", iso2: "IL", callingCode: "+972" },
  { country: "Turkey", iso2: "TR", callingCode: "+90" },
  { country: "Germany", iso2: "DE", callingCode: "+49" },
  { country: "France", iso2: "FR", callingCode: "+33" },
  { country: "Spain", iso2: "ES", callingCode: "+34" },
  { country: "Italy", iso2: "IT", callingCode: "+39" },
  { country: "Netherlands", iso2: "NL", callingCode: "+31" },
  { country: "Belgium", iso2: "BE", callingCode: "+32" },
  { country: "Switzerland", iso2: "CH", callingCode: "+41" },
  { country: "Austria", iso2: "AT", callingCode: "+43" },
  { country: "Ireland", iso2: "IE", callingCode: "+353" },
  { country: "Portugal", iso2: "PT", callingCode: "+351" },
  { country: "Sweden", iso2: "SE", callingCode: "+46" },
  { country: "Norway", iso2: "NO", callingCode: "+47" },
  { country: "Denmark", iso2: "DK", callingCode: "+45" },
  { country: "Finland", iso2: "FI", callingCode: "+358" },
  { country: "Poland", iso2: "PL", callingCode: "+48" },
  { country: "Czech Republic", iso2: "CZ", callingCode: "+420" },
  { country: "Greece", iso2: "GR", callingCode: "+30" },
  { country: "Romania", iso2: "RO", callingCode: "+40" },
  { country: "Hungary", iso2: "HU", callingCode: "+36" },
  { country: "Ukraine", iso2: "UA", callingCode: "+380" },
  { country: "Russia", iso2: "RU", callingCode: "+7" },
  { country: "Brazil", iso2: "BR", callingCode: "+55" },
  { country: "Mexico", iso2: "MX", callingCode: "+52" },
  { country: "Argentina", iso2: "AR", callingCode: "+54" },
  { country: "Chile", iso2: "CL", callingCode: "+56" },
  { country: "Colombia", iso2: "CO", callingCode: "+57" },
  { country: "Peru", iso2: "PE", callingCode: "+51" },
  { country: "Venezuela", iso2: "VE", callingCode: "+58" },
  { country: "Ecuador", iso2: "EC", callingCode: "+593" },
  { country: "Uruguay", iso2: "UY", callingCode: "+598" },
  { country: "Paraguay", iso2: "PY", callingCode: "+595" },
  { country: "Bolivia", iso2: "BO", callingCode: "+591" },
  { country: "South Africa", iso2: "ZA", callingCode: "+27" },
  { country: "Nigeria", iso2: "NG", callingCode: "+234" },
  { country: "Kenya", iso2: "KE", callingCode: "+254" },
  { country: "Ghana", iso2: "GH", callingCode: "+233" },
  { country: "Egypt", iso2: "EG", callingCode: "+20" },
  { country: "Morocco", iso2: "MA", callingCode: "+212" },
  { country: "Algeria", iso2: "DZ", callingCode: "+213" },
  { country: "Tunisia", iso2: "TN", callingCode: "+216" },
  { country: "Ethiopia", iso2: "ET", callingCode: "+251" },
  { country: "Uganda", iso2: "UG", callingCode: "+256" },
  { country: "Tanzania", iso2: "TZ", callingCode: "+255" },
  { country: "Zimbabwe", iso2: "ZW", callingCode: "+263" },
  { country: "Zambia", iso2: "ZM", callingCode: "+260" },
  { country: "Botswana", iso2: "BW", callingCode: "+267" },
  { country: "Rwanda", iso2: "RW", callingCode: "+250" },
  { country: "Jamaica", iso2: "JM", callingCode: "+1" },
  { country: "Dominican Republic", iso2: "DO", callingCode: "+1" },
  { country: "Puerto Rico", iso2: "PR", callingCode: "+1" },
  { country: "Trinidad and Tobago", iso2: "TT", callingCode: "+1" },
];

export const COUNTRY_CALLING_CODES_BY_LENGTH_DESC = [...COUNTRY_CALLING_CODES].sort(
  (left, right) => right.callingCode.length - left.callingCode.length,
);
